### ISSUE TITLE
[pytorch] Add PyTorch backend integration

### ISSUE THREAD

**Issue by fg-mindee** [mindee/doctr#261]
Integrating PyTorch as a possible backend is a natural evolution of DocTR. Two questions need to be answered though, I added some suggestions.

## How do we add the PyTorch counterpart of an object / class / function?
For module `my_module.py`, 
- we create `my_module.tf.py` and put the rest in `my_module.pt.py`. If there are non framework-related features, they can be kept in `my_module`. The latter will reference the tf or pytorch implementation depending on the ibrary build
- we add a folder for each framework, and put the module named the same way in each folder for each framework.

## Where do we start?
Here are my thoughts on all DocTR modules:
- `datasets`: the `loader.py` module and the call of each dataset
- `documents`: nothing framework-specific
- `models`: every module will be impacted
- `transforms`: the call methods will be impacted if we cannot used plain torchvision transforms
- `utils`: nothing framework-specific

## How do we ensure that each build is running correctly?
- edit the `setup.py` to build the specified version
- add CI jobs to run the installation for each framework (probably will have to rethink unittests for each separate framework build)

## Next steps
- [x] Enable flexible framework selection for build & imports (#306, #314, #315)
- [x] PyTorch mirror of doctr.datasets (#319)
- [x] PyTorch mirror of doctr.models
    - [x] doctr.models.preprocessor (#313)
    - [x] doctr.models.backbones (#327, #328)
    - [x] doctr.models.utils (#323)
    - [x] doctr.models.detection (#310, #313, #316, #317)
    - [x] doctr.models.recognition (#318, #329, #333, #335, #340, #342)
- [x] PyTorch mirror of doctr.transforms (#313, #322)

**Comment by fg-mindee** [comment]
Closing this since ONNX support and reference script are a bit far off from this PR
