### ISSUE TITLE
[models] Add a pretrained checkpoint loading mechanism

### ISSUE THREAD

**Issue by fg-mindee** [mindee/doctr#41]
Architecture definitions are already available in the repo, but it still lacks a way to load a set of pretrained parameters. This should be tackled for the upcoming release. Here are the requirements:
- [x] Select a checkpoint format: `.ckpt`
- [x] Implement necessary methods/functions to save and load the checkpoint: keras inherited (#49)
- [x] Ensure data integrity (SHA256 hash most likely) (#49)
- [x] Add a first pretrained model (#49)
