### ISSUE TITLE
[scripts] Adding scripts to easily evaluate the latency of models

### ISSUE THREAD

**Issue by fg-mindee** [mindee/doctr#699]
As discussed, we need to provide means to accurately evaluate the latency of models in a given environment. This comes with several challenges and questions:
- 1 script per framework?
- 1 script per task? (text detection, object detection, text recognition)
- should we benchmark the predictor or the DL model only? (for OCR we don't have any end-to-end DL model for instance, so that )

I would suggest focusing on mid-level tasks (excluding OCR for now since we don't have an end-to-end archi) and implementing:
- [ ] Text Detection benchmark script (#746)
- [ ] Text Recognition benchmark script (#746)
- [ ] Object Detection benchmark script (#746)
 
What do you think @charlesmindee?
