### ISSUE TITLE
[transforms] Extends the list of supported data augmentations

### ISSUE THREAD

**Issue by fg-mindee** [mindee/doctr#730]
As discussed in #654, the artefact detection needs to improve its robustness. In order to do so and prevent overfitting, I would suggest gradually extending the list of our supported transformations:
- [x] uniform photometric transformations (noise, blur, etc.) #758 #654 #768 #771
- [x] non-uniform photometric transformations (shadows, etc.) #811 
- [ ] geometric transformations (flips, rotations, crops, etc.) #773 #799

Ideally, a given transform should be implemented in `doctr/transforms/modules` so that with the corresponding backend, we can do:
```python
transfo = ....
pil_img = ... 
augmented_img = transfo(pil_img)
```
for transformations that only change the image.

and:
```python
transfo = ....
pil_img = ... 
target = {...}
augmented_img, augmented_target = transfo(pil_img, target)
```
for transformations that alter the target. In doing so, that will work nicely with our Dataloaders :+1:

**Comment by felixdittrich92** [comment]
@frgfm only @SiddhantBahuguna PR left or do you have other augmentations in mind ? :)

**Comment by frgfm** [comment]
For now, I think the random perspective would be the last one required yeah :+1:

**Comment by felixdittrich92** [comment]
Hi @SiddhantBahuguna any way in near future that you finish your draft PR ? :)

**Comment by SiddhantBahuguna** [comment]
> Hi @SiddhantBahuguna any way in near future that you finish your draft PR ? :) Or should we keep it free to take ?

Greetings @felixdittrich92 , I am really sorry for the unwanted delay. 
I will get it done this week positively :) Sorry again !

**Comment by felixdittrich92** [comment]
Sounds nice :hugs: :+1:

**Comment by felixdittrich92** [comment]
@SiddhantBahuguna Do you think you could finish your PR that we can close this ? :)

**Comment by felixdittrich92** [comment]
@odulcy-mindee I think we can close this ?
I don't see any issues with different perspectives (detection models) your dataset seems to capture this already well.
Or do you think we should add RandomPerspective as last one ftm ?

**Comment by odulcy-mindee** [comment]
Yeah, this issue can be closed, that's fine
