### ISSUE TITLE
Release tracker - v0.5.1

### ISSUE THREAD

**Issue by fg-mindee** [mindee/doctr#788]
This issue is to be used to track the roadmap of docTR for release v0.5.1.

- Models
    - [ ] Bridge the gap between TensorFlow & PyTorch support of text detection on rotation
- Transforms
    - [x] Harmonize `RandomRotate` between PyTorch & TensorFlow #784 
    - [x] Add missing TensorFlow support for docTR transforms #779

**Comment by charlesmindee** [comment]
Closing this since the released has been done

**Comment by felixdittrich92** [comment]
@charlesmindee 
pin sar/master fix to 0.6.0 ? :)
