### ISSUE TITLE
Release tracker - v0.6.0

### ISSUE THREAD

**Issue by fg-mindee** [mindee/doctr#791]
This issue is to be used to track the roadmap of docTR for release v0.6.0, and collect feedback from users & contributors.

For the v0.5.2 roadmap, please see #967

- Datasets
    - [x] #587
    - [x] Unify localization target to relative coordinates #775
    - [x] #935
    - [x] #955
    - [x] #827
    - [x] #782
    - [x] #987 
    - [x] #594 #889 #891 
    - [x] #955 
    - [x] #927
    - [x] #956
    - [x] #1038 
    - [x] #1041 

- Models 
    - [x] #789
    - [x] #819
    - [x] #563
    - [x] #808
    - [x] #883 
    - [x] #544
    - [x] #836 #892 #881 #896 
    - [x] #979 #980 #976 
    - [x] #991
    - [x] #902
    - [x] #960
    - [x] #964
    - [x] #1039
    - [x] #1013 
    - [x] #1050 #1055 #1063 #1059 #1072 
    - [x] #1061
    - [x] #1022 
    - [x] #1023 

- IO
    - [x] #947
    - [x] #953
    - [x] #944 
    - [x] #1019 

- Documentation
    - [x] Improves the general appearance of the documentation (cf. #851)
    - [x] #901 
    - [x] #959
    - [x] #936
    - [x] #937
    - [x] #983 
    - [x] #856, #859, #857, #862, #861
    - [x] #905
    - [x] #904
    - [x] #921 
    - [x] #901
    - [x] #937
    - [x] #958
    - [x] #929
    - [x] #993 
    - [x] #938 
    - [x] #959 
    - [x] #1070 
    - [x] #1002 
    - [x] #1017 
    - [x] #1076 
 
- References
    - [x] Add support of AMP for training in both frameworks #263
    - [x] #933 
    - [x] #696
    - [x] #263 
    - [x] #1062
 
- Tests
    - [x] Mock dataset for testing instead of downloading subsamples #680 
    - [x] #903 
    - [x] #680 
    - [x] #1054 

- Demo
    - [x] #658 
    - [x] #951 

- Code quality
    -[x] #953 

- Build
    - [x] #957
    - [x] #454
    - [x] #932 
    - [x] #998 
    - [x] #963 
    - [x] #966 
    - [x] #1033 
    - [x] #1034 
    - [x] #1031 
    - [x] #1028
    - [x] #1030  

- CI
    - [x] #853 
    - [x] #727

- Scripts
    - [x] #699 
    - [x] #999 
    - [x] #1060 

- API
    - [x] #847 (#997)

- Backlog from v0.5.1:
    - [x] #802 #920 #925 #941 #949 #960 #964 #986 #975

**Comment by frgfm** [comment]
Which ones @felixdittrich92 ? I had left out some on purpose when we are "awaiting response" from the issue author

For the rest, I linked the issue rather than the PR (when the PR points to the issue) to avoid floading

**Comment by felixdittrich92** [comment]
@frgfm cannot add this currently (on mobile phone) but there was all HF hub integration PRs missing in 0.6 milestone and same for recognition dataset support

**Comment by felixdittrich92** [comment]
@frgfm updated should be complete now :)

**Comment by felixdittrich92** [comment]
@frgfm updated :) hopefully i don't missed anything :sweat_smile:

**Comment by felixdittrich92** [comment]
released
